### ISSUE TITLE
Can't access the Kibana server

### ISSUE THREAD

**Issue by kandadaboggu** [omc/heroku-kibana#2]
I have set the `ELASTICSEARCH_URL` to a Bonsai elastic search instance. The ElasticSearch instance is accessible to my other apps.
I get the following error when I try to access the Kibana interface.

``` ruby
{
    "name": "Kibana",
    "hostname": "XXXX",
    "pid": 3,
    "level": 50,
    "err": {
        "message": "Cluster not found. It may take a few moments for new clusters to be created. Please contact support @bonsai.io for further assistance.",
        "name": "Error",
        "stack": "Error: Cluster not found. It may take a few moments for new clusters to be created. Please contact support@bonsai.io for further assistance.\n    at respond (/app/kibana-4.1.3-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:235:15)\n    at checkRespForFailure (/app/kibana-4.1.3-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n    at HttpConnector.<anonymous> (/app/kibana-4.1.3-linux-x64/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n    at IncomingMessage.bound (/app/kibana-4.1.3-linux-x64/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)"
    },
    "msg": "",
    "time": "2016-01-29T04:05:51.664Z",
    "v": 0
}
```

**Comment by robsears** [comment]
Mind shooting an email to support@bonsai.io with the cluster URL you're using?
